export const MOTION_LOCALES = ['en', 'ko', 'ja', 'zh', 'es', 'fr', 'de', 'pt', 'ru'] as const;
export type MotionLocale = (typeof MOTION_LOCALES)[number];

export type MotionCopy = {
  liveKicker: string;
  bugGone: string;
  noRepro: string;
  rewindIt: string;
  noRerun: string;
  rewindMoment: string;
  pickReal: string;
  objectOrManual: string;
  objectPick: string;
  manualNote: string;
  saveChanges: string;
  button: string;
  visibleAgo: string;
  manualQuote: string;
  packKicker: string;
  packTitle: string;
  momentBefore: string;
  nameRoleState: string;
  yourAnnotation: string;
  aiReady: string;
  aiExact: string;
  aiRealObject: string;
  aiWhatMeant: string;
  noGuess: string;
  endTime: string;
  oneFrame: string;
  moreThan: string;
  capturePixels: string;
  addMeaning: string;
  nonDestructive: string;
  pixelsOriginal: string;
  contextEditable: string;
  separateLayer: string;
  wholeExplanation: string;
  originalPixels: string;
  boxesNotes: string;
  aiUnderstands: string;
  aiQuote: string;
  originalUntouched: string;
  explanationBeside: string;
  endStill: string;
};

export const COPY: Record<MotionLocale, MotionCopy> = {
  en: {
    liveKicker: 'LIVE RECORDING · LAST 30s',
    bugGone: 'The bug is\nalready gone.',
    noRepro: 'Don’t reproduce it.',
    rewindIt: 'Rewind it.',
    noRerun: 'NO RE-RUN',
    rewindMoment: 'Rewind the moment.',
    pickReal: 'PICK THE REAL OBJECT',
    objectOrManual: 'OBJECT OR MANUAL · BOTH STAY EDITABLE',
    objectPick: 'OBJECT PICK',
    manualNote: 'MANUAL NOTE',
    saveChanges: 'Save',
    button: 'Button',
    visibleAgo: 'Visible at −8.2s',
    manualQuote: '“This disappeared after retry.”',
    packKicker: 'ONE PACK · COMPLETE CONTEXT',
    packTitle: 'Replay + object + intent.',
    momentBefore: 'The moment before',
    nameRoleState: 'Name · role · state',
    yourAnnotation: 'Your annotation',
    aiReady: 'AI-READY CONTEXT',
    aiExact: 'The exact moment.',
    aiRealObject: 'The real object.',
    aiWhatMeant: 'What you meant.',
    noGuess: 'No guessing from pixels alone.',
    endTime: 'No re-run. Rewind. Pick. Explain.',
    oneFrame: 'ONE FRAME · SAME CONTEXT',
    moreThan: 'More than\na screenshot.',
    capturePixels: 'Capture the pixels.',
    addMeaning: 'Add what they mean.',
    nonDestructive: 'NON-DESTRUCTIVE BY DESIGN',
    pixelsOriginal: 'Pixels stay original.',
    contextEditable: 'Context stays editable.',
    separateLayer: 'SEPARATE LAYER',
    wholeExplanation: 'Give AI the whole explanation.',
    originalPixels: 'Original pixels',
    boxesNotes: 'Boxes + notes',
    aiUnderstands: 'AI UNDERSTANDS',
    aiQuote: '“The Save button failed after the retry.\nThis red box is the symptom.”',
    originalUntouched: 'Original image untouched.',
    explanationBeside: 'Explanation carried beside it.',
    endStill: 'Original pixels. Editable context. Better answers.',
  },
  ko: {
    liveKicker: '라이브 녹화 · 최근 30초',
    bugGone: '버그는 이미\n사라졌습니다.',
    noRepro: '다시 재현하지 마세요.',
    rewindIt: '되감으면 됩니다.',
    noRerun: '재실행 필요 없음',
    rewindMoment: '문제가 난 순간으로 되감기.',
    pickReal: '실제 UI 객체 선택',
    objectOrManual: '객체 선택 또는 수동 메모 · 모두 편집 가능',
    objectPick: '객체 선택',
    manualNote: '수동 메모',
    saveChanges: '저장',
    button: '버튼',
    visibleAgo: '8.2초 전에 보임',
    manualQuote: '“재시도 후 사라졌습니다.”',
    packKicker: '하나의 팩 · 완전한 맥락',
    packTitle: '리플레이 + 객체 + 의도.',
    momentBefore: '문제 직전의 순간',
    nameRoleState: '이름 · 역할 · 상태',
    yourAnnotation: '사용자의 설명',
    aiReady: 'AI가 읽는 맥락',
    aiExact: '정확한 순간.',
    aiRealObject: '실제 객체.',
    aiWhatMeant: '사용자가 뜻한 것.',
    noGuess: '픽셀만 보고 추측할 필요가 없습니다.',
    endTime: '재현하지 말고, 되감고, 선택하고, 설명하세요.',
    oneFrame: '한 장 · 같은 맥락',
    moreThan: '스크린샷\n그 이상.',
    capturePixels: '픽셀을 캡처하고.',
    addMeaning: '무엇을 뜻하는지 더하세요.',
    nonDestructive: '원본을 건드리지 않는 설계',
    pixelsOriginal: '픽셀은 원본 그대로.',
    contextEditable: '맥락은 계속 편집 가능.',
    separateLayer: '별도 레이어',
    wholeExplanation: 'AI에게 설명 전체를 전달하세요.',
    originalPixels: '원본 픽셀',
    boxesNotes: '상자 + 메모',
    aiUnderstands: 'AI가 이해함',
    aiQuote: '“재시도 후 저장 버튼이 실패했습니다.\n빨간 상자가 증상입니다.”',
    originalUntouched: '원본 이미지는 그대로입니다.',
    explanationBeside: '설명은 이미지 옆에 보존됩니다.',
    endStill: '원본 픽셀. 편집 가능한 맥락. 더 나은 답변.',
  },
  ja: {
    liveKicker: 'ライブ録画 · 直近30秒',
    bugGone: 'バグはもう\n消えています。',
    noRepro: '再現し直す必要はありません。',
    rewindIt: '巻き戻せばいい。',
    noRerun: '再実行は不要',
    rewindMoment: 'その瞬間まで巻き戻す。',
    pickReal: '本物のUIオブジェクトを選択',
    objectOrManual: 'オブジェクト選択も手動メモも編集可能',
    objectPick: 'オブジェクト選択',
    manualNote: '手動メモ',
    saveChanges: '保存',
    button: 'ボタン',
    visibleAgo: '8.2秒前に表示',
    manualQuote: '「再試行後に消えました」',
    packKicker: '1つのパック · 完全なコンテキスト',
    packTitle: 'リプレイ + オブジェクト + 意図。',
    momentBefore: '直前の瞬間',
    nameRoleState: '名前 · ロール · 状態',
    yourAnnotation: 'あなたの注釈',
    aiReady: 'AI向けコンテキスト',
    aiExact: '正確な瞬間。',
    aiRealObject: '本物のオブジェクト。',
    aiWhatMeant: 'あなたの意図。',
    noGuess: 'ピクセルだけから推測する必要はありません。',
    endTime: '再現せず、巻き戻し、選び、説明する。',
    oneFrame: '1枚 · 同じコンテキスト',
    moreThan: 'スクリーンショット\n以上のもの。',
    capturePixels: 'ピクセルを取り込み、',
    addMeaning: '意味を加える。',
    nonDestructive: '非破壊設計',
    pixelsOriginal: 'ピクセルはオリジナルのまま。',
    contextEditable: 'コンテキストは編集可能。',
    separateLayer: '別レイヤー',
    wholeExplanation: 'AIに説明全体を渡す。',
    originalPixels: '元のピクセル',
    boxesNotes: '枠 + メモ',
    aiUnderstands: 'AIが理解',
    aiQuote: '「再試行後に保存ボタンが失敗しました。\n赤い枠が症状です」',
    originalUntouched: '元画像は変更されません。',
    explanationBeside: '説明は画像の隣に保持されます。',
    endStill: '元のピクセル。編集可能な文脈。より良い回答。',
  },
  zh: {
    liveKicker: '实时录制 · 最近30秒',
    bugGone: '问题已经\n消失了。',
    noRepro: '无需重新复现。',
    rewindIt: '直接回溯。',
    noRerun: '无需重现',
    rewindMoment: '回到问题发生的那一刻。',
    pickReal: '选择真实的UI对象',
    objectOrManual: '对象选择或手动备注 · 均可编辑',
    objectPick: '对象选择',
    manualNote: '手动备注',
    saveChanges: '保存',
    button: '按钮',
    visibleAgo: '8.2秒前可见',
    manualQuote: '“重试后它消失了。”',
    packKicker: '一个包 · 完整上下文',
    packTitle: '回放 + 对象 + 意图。',
    momentBefore: '问题发生前一刻',
    nameRoleState: '名称 · 角色 · 状态',
    yourAnnotation: '你的标注',
    aiReady: 'AI可读上下文',
    aiExact: '准确的时刻。',
    aiRealObject: '真实的对象。',
    aiWhatMeant: '你的真实意图。',
    noGuess: '不必只看像素猜测。',
    endTime: '无需重现。回溯、选择、说明。',
    oneFrame: '一张图 · 同样的上下文',
    moreThan: '不只是\n一张截图。',
    capturePixels: '捕获像素。',
    addMeaning: '补充它们的含义。',
    nonDestructive: '非破坏式设计',
    pixelsOriginal: '像素保持原样。',
    contextEditable: '上下文仍可编辑。',
    separateLayer: '独立图层',
    wholeExplanation: '把完整说明交给AI。',
    originalPixels: '原始像素',
    boxesNotes: '框选 + 备注',
    aiUnderstands: 'AI已理解',
    aiQuote: '“重试后保存按钮失败。\n红框标出了问题。”',
    originalUntouched: '原始图像保持不变。',
    explanationBeside: '说明与图像并列保存。',
    endStill: '原始像素。可编辑上下文。更好的答案。',
  },
  es: {
    liveKicker: 'GRABACIÓN ACTIVA · ÚLTIMOS 30s',
    bugGone: 'El fallo ya\nha desaparecido.',
    noRepro: 'No lo reproduzcas.',
    rewindIt: 'Rebobina.',
    noRerun: 'SIN REPETIR EL FALLO',
    rewindMoment: 'Vuelve al momento exacto.',
    pickReal: 'ELIGE EL OBJETO REAL',
    objectOrManual: 'OBJETO O NOTA · TODO SIGUE EDITABLE',
    objectPick: 'ELEGIR OBJETO',
    manualNote: 'NOTA MANUAL',
    saveChanges: 'Guardar',
    button: 'Botón',
    visibleAgo: 'Visible hace 8,2 s',
    manualQuote: '«Desapareció tras reintentar.»',
    packKicker: 'UN PACK · CONTEXTO COMPLETO',
    packTitle: 'Replay + objeto + intención.',
    momentBefore: 'El momento anterior',
    nameRoleState: 'Nombre · rol · estado',
    yourAnnotation: 'Tu anotación',
    aiReady: 'CONTEXTO PARA IA',
    aiExact: 'El momento exacto.',
    aiRealObject: 'El objeto real.',
    aiWhatMeant: 'Lo que querías decir.',
    noGuess: 'Sin adivinar solo por los píxeles.',
    endTime: 'No repitas. Rebobina. Elige. Explica.',
    oneFrame: 'UN FOTOGRAMA · MISMO CONTEXTO',
    moreThan: 'Más que una\ncaptura.',
    capturePixels: 'Captura los píxeles.',
    addMeaning: 'Añade lo que significan.',
    nonDestructive: 'DISEÑO NO DESTRUCTIVO',
    pixelsOriginal: 'Los píxeles quedan intactos.',
    contextEditable: 'El contexto sigue editable.',
    separateLayer: 'CAPA SEPARADA',
    wholeExplanation: 'Dale a la IA toda la explicación.',
    originalPixels: 'Píxeles originales',
    boxesNotes: 'Cajas + notas',
    aiUnderstands: 'LA IA ENTIENDE',
    aiQuote: '«Guardar falló tras reintentar.\nLa caja roja marca el síntoma.»',
    originalUntouched: 'Imagen original intacta.',
    explanationBeside: 'La explicación viaja a su lado.',
    endStill: 'Píxeles originales. Contexto editable. Mejores respuestas.',
  },
  fr: {
    liveKicker: 'ENREGISTREMENT ACTIF · 30s',
    bugGone: 'Le bug a déjà\ndisparu.',
    noRepro: 'Ne le reproduisez pas.',
    rewindIt: 'Remontez le temps.',
    noRerun: 'SANS REPRODUIRE',
    rewindMoment: 'Revenez au moment exact.',
    pickReal: 'SÉLECTIONNEZ LE VRAI OBJET',
    objectOrManual: 'OBJET OU NOTE · TOUT RESTE MODIFIABLE',
    objectPick: 'CHOIX DE L’OBJET',
    manualNote: 'NOTE MANUELLE',
    saveChanges: 'Enregistrer',
    button: 'Bouton',
    visibleAgo: 'Visible il y a 8,2 s',
    manualQuote: '«Disparu après la nouvelle tentative.»',
    packKicker: 'UN PACK · CONTEXTE COMPLET',
    packTitle: 'Replay + objet + intention.',
    momentBefore: 'Le moment précédent',
    nameRoleState: 'Nom · rôle · état',
    yourAnnotation: 'Votre annotation',
    aiReady: 'CONTEXTE POUR L’IA',
    aiExact: 'Le moment exact.',
    aiRealObject: 'Le véritable objet.',
    aiWhatMeant: 'Ce que vous vouliez dire.',
    noGuess: 'Plus besoin de deviner à partir des pixels.',
    endTime: 'Sans reproduire. Remontez. Choisissez. Expliquez.',
    oneFrame: 'UNE IMAGE · MÊME CONTEXTE',
    moreThan: 'Plus qu’une\ncapture d’écran.',
    capturePixels: 'Capturez les pixels.',
    addMeaning: 'Ajoutez leur signification.',
    nonDestructive: 'CONCEPTION NON DESTRUCTIVE',
    pixelsOriginal: 'Les pixels restent intacts.',
    contextEditable: 'Le contexte reste modifiable.',
    separateLayer: 'CALQUE SÉPARÉ',
    wholeExplanation: 'Donnez toute l’explication à l’IA.',
    originalPixels: 'Pixels originaux',
    boxesNotes: 'Cadres + notes',
    aiUnderstands: 'L’IA COMPREND',
    aiQuote: '«L’enregistrement a échoué après la relance.\nLe cadre rouge montre le symptôme.»',
    originalUntouched: 'Image originale intacte.',
    explanationBeside: 'L’explication reste à côté.',
    endStill: 'Pixels originaux. Contexte modifiable. Meilleures réponses.',
  },
  de: {
    liveKicker: 'LIVE-AUFNAHME · LETZTE 30s',
    bugGone: 'Der Fehler ist\nschon weg.',
    noRepro: 'Nicht nachstellen.',
    rewindIt: 'Zurückspulen.',
    noRerun: 'NICHT ERNEUT AUSFÜHREN',
    rewindMoment: 'Zum exakten Moment zurück.',
    pickReal: 'DAS ECHTE OBJEKT WÄHLEN',
    objectOrManual: 'OBJEKT ODER NOTIZ · ALLES BLEIBT EDITIERBAR',
    objectPick: 'OBJEKT WÄHLEN',
    manualNote: 'MANUELLE NOTIZ',
    saveChanges: 'Speichern',
    button: 'Schaltfläche',
    visibleAgo: 'Vor 8,2 s sichtbar',
    manualQuote: '„Nach dem Wiederholen verschwunden.“',
    packKicker: 'EIN PACK · VOLLSTÄNDIGER KONTEXT',
    packTitle: 'Replay + Objekt + Absicht.',
    momentBefore: 'Der Moment davor',
    nameRoleState: 'Name · Rolle · Zustand',
    yourAnnotation: 'Ihre Anmerkung',
    aiReady: 'KI-FERTIGER KONTEXT',
    aiExact: 'Der exakte Moment.',
    aiRealObject: 'Das echte Objekt.',
    aiWhatMeant: 'Was Sie gemeint haben.',
    noGuess: 'Kein Raten nur anhand von Pixeln.',
    endTime: 'Nicht nachstellen. Zurückspulen. Wählen. Erklären.',
    oneFrame: 'EIN BILD · GLEICHER KONTEXT',
    moreThan: 'Mehr als ein\nScreenshot.',
    capturePixels: 'Pixel erfassen.',
    addMeaning: 'Ihre Bedeutung ergänzen.',
    nonDestructive: 'NICHT-DESTRUKTIVES DESIGN',
    pixelsOriginal: 'Die Pixel bleiben original.',
    contextEditable: 'Der Kontext bleibt editierbar.',
    separateLayer: 'SEPARATE EBENE',
    wholeExplanation: 'Der KI die ganze Erklärung geben.',
    originalPixels: 'Originalpixel',
    boxesNotes: 'Rahmen + Notizen',
    aiUnderstands: 'DIE KI VERSTEHT',
    aiQuote: '„Speichern schlug nach dem Versuch fehl.\nDer rote Rahmen zeigt das Symptom.“',
    originalUntouched: 'Originalbild unverändert.',
    explanationBeside: 'Die Erklärung bleibt daneben.',
    endStill: 'Originalpixel. Editierbarer Kontext. Bessere Antworten.',
  },
  pt: {
    liveKicker: 'GRAVAÇÃO ATIVA · ÚLTIMOS 30s',
    bugGone: 'O erro já\nsumiu.',
    noRepro: 'Não reproduza de novo.',
    rewindIt: 'Volte no tempo.',
    noRerun: 'SEM REPRODUZIR',
    rewindMoment: 'Volte ao momento exato.',
    pickReal: 'SELECIONE O OBJETO REAL',
    objectOrManual: 'OBJETO OU NOTA · TUDO CONTINUA EDITÁVEL',
    objectPick: 'SELECIONAR OBJETO',
    manualNote: 'NOTA MANUAL',
    saveChanges: 'Salvar',
    button: 'Botão',
    visibleAgo: 'Visível há 8,2 s',
    manualQuote: '“Sumiu depois de tentar de novo.”',
    packKicker: 'UM PACK · CONTEXTO COMPLETO',
    packTitle: 'Replay + objeto + intenção.',
    momentBefore: 'O momento anterior',
    nameRoleState: 'Nome · papel · estado',
    yourAnnotation: 'Sua anotação',
    aiReady: 'CONTEXTO PARA IA',
    aiExact: 'O momento exato.',
    aiRealObject: 'O objeto real.',
    aiWhatMeant: 'O que você quis dizer.',
    noGuess: 'Sem adivinhar só pelos pixels.',
    endTime: 'Não reproduza. Volte. Selecione. Explique.',
    oneFrame: 'UM QUADRO · MESMO CONTEXTO',
    moreThan: 'Mais que uma\ncaptura de tela.',
    capturePixels: 'Capture os pixels.',
    addMeaning: 'Adicione o que significam.',
    nonDestructive: 'DESIGN NÃO DESTRUTIVO',
    pixelsOriginal: 'Os pixels ficam originais.',
    contextEditable: 'O contexto continua editável.',
    separateLayer: 'CAMADA SEPARADA',
    wholeExplanation: 'Dê à IA a explicação completa.',
    originalPixels: 'Pixels originais',
    boxesNotes: 'Caixas + notas',
    aiUnderstands: 'A IA ENTENDE',
    aiQuote: '“Salvar falhou após tentar de novo.\nA caixa vermelha mostra o sintoma.”',
    originalUntouched: 'Imagem original intacta.',
    explanationBeside: 'A explicação fica ao lado.',
    endStill: 'Pixels originais. Contexto editável. Respostas melhores.',
  },
  ru: {
    liveKicker: 'ФОНОВАЯ ЗАПИСЬ · 30с',
    bugGone: 'Ошибка уже\nисчезла.',
    noRepro: 'Не воспроизводите заново.',
    rewindIt: 'Перемотайте назад.',
    noRerun: 'БЕЗ ПОВТОРНОГО ЗАПУСКА',
    rewindMoment: 'Вернитесь к точному моменту.',
    pickReal: 'ВЫБЕРИТЕ РЕАЛЬНЫЙ ОБЪЕКТ',
    objectOrManual: 'ОБЪЕКТ ИЛИ ЗАМЕТКА · ВСЁ РЕДАКТИРУЕТСЯ',
    objectPick: 'ВЫБОР ОБЪЕКТА',
    manualNote: 'РУЧНАЯ ЗАМЕТКА',
    saveChanges: 'Сохранить',
    button: 'Кнопка',
    visibleAgo: 'Видима 8,2 с назад',
    manualQuote: '«Исчезло после повторной попытки.»',
    packKicker: 'ОДИН ПАКЕТ · ПОЛНЫЙ КОНТЕКСТ',
    packTitle: 'Повтор + объект + намерение.',
    momentBefore: 'Момент до ошибки',
    nameRoleState: 'Имя · роль · состояние',
    yourAnnotation: 'Ваша аннотация',
    aiReady: 'КОНТЕКСТ ДЛЯ ИИ',
    aiExact: 'Точный момент.',
    aiRealObject: 'Реальный объект.',
    aiWhatMeant: 'Что вы имели в виду.',
    noGuess: 'Не нужно гадать только по пикселям.',
    endTime: 'Не повторяйте. Перемотайте. Выберите. Объясните.',
    oneFrame: 'ОДИН КАДР · ТОТ ЖЕ КОНТЕКСТ',
    moreThan: 'Больше, чем\nскриншот.',
    capturePixels: 'Сохраните пиксели.',
    addMeaning: 'Добавьте их смысл.',
    nonDestructive: 'НЕРАЗРУШАЮЩАЯ СХЕМА',
    pixelsOriginal: 'Пиксели остаются исходными.',
    contextEditable: 'Контекст остаётся редактируемым.',
    separateLayer: 'ОТДЕЛЬНЫЙ СЛОЙ',
    wholeExplanation: 'Передайте ИИ полное объяснение.',
    originalPixels: 'Исходные пиксели',
    boxesNotes: 'Рамки + заметки',
    aiUnderstands: 'ИИ ПОНИМАЕТ',
    aiQuote: '«После повтора сохранение не сработало.\nКрасная рамка показывает симптом.»',
    originalUntouched: 'Исходное изображение не изменено.',
    explanationBeside: 'Объяснение хранится рядом.',
    endStill: 'Исходные пиксели. Редактируемый контекст. Лучшие ответы.',
  },
};

export const localeFontFamily = (locale: MotionLocale) => {
  if (locale === 'ko') return 'Malgun Gothic, Noto Sans KR, sans-serif';
  if (locale === 'ja') return 'Yu Gothic, Meiryo, Noto Sans JP, sans-serif';
  if (locale === 'zh') return 'Microsoft YaHei, Noto Sans SC, sans-serif';
  return 'Segoe UI, Inter, Arial, sans-serif';
};

export const safeLocale = (locale?: string): MotionLocale =>
  MOTION_LOCALES.includes(locale as MotionLocale) ? (locale as MotionLocale) : 'en';
